language: php
php:
  - '7.0'
  - '5.6'
  - hhvm
before_script:
  - composer self-update
  - composer install --prefer-source
  - wget https://scrutinizer-ci.com/ocular.phar
script: phpunit

after_script:
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml


